modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/davidjjung/changeofcart/issues"
license = "MIT License"

[[mods]]
modId = "change_of_cart"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "minecraft:minecart"
configBackground = "minecraft:textures/block/gravel.png"
authors = "DavigJ"
credits = "Credits to Zym for the mod concept. Thanks to Jsburg and tallestred for code assistance"
displayURL = "https://github.com/davidjjung/changeofcart"
displayName = "Change of Cart"
description = '''
    Minecart QoL. Muffle carts with wax/wool, or reduce friction using gravel bedding.
    '''

[[dependencies.change_of_cart]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.change_of_cart]]
modId = "forge"
mandatory = true
versionRange = "[43.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.change_of_cart]]
modId = "blueprint"
mandatory = true
versionRange = "[6.2.0,)"
ordering = "AFTER"
side = "BOTH"