modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/davidjjung/changeofcart/issues"
license = "MIT License"

[[mixins]]
config = "change_of_cart.mixins.json"

[[mods]]
modId = "change_of_cart"
version = "${mod_version}"
logoFile = "logo.png"
itemIcon = "minecraft:minecart"
configBackground = "minecraft:textures/block/white_wool.png"
authors = "DavigJ"
credits = "Credits to Zym for the mod concept. Thanks to Jsburg and tallestred for code assistance"
displayURL = "https://modrinth.com/project/change-of-cart"
displayName = "Change of Cart"
description = '''
    Minecart QoL. Muffle carts with wax/wool, or reduce friction using gravel bedding.
    '''

[[dependencies.change_of_cart]]
modId = "minecraft"
type = "required"
versionRange = "[${mc_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.change_of_cart]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.change_of_cart]]
modId = "blueprint"
type = "required"
versionRange = "[${blueprint},)"
ordering = "AFTER"
side = "BOTH"